"""
Seed data for jurisdictions, frameworks, and requirements.

Legal content here is a summarised, best-effort paraphrase drawn from public
sources and is NOT legal advice. Organisations must have counsel review.
"""

JURISDICTIONS = [
    {
        'code': 'EU',
        'name': 'European Union / EEA',
        'region': 'Europe',
        'authority': 'European Data Protection Board (and national DPAs)',
        'authority_url': 'https://edpb.europa.eu/',
        'flag_emoji': '🇪🇺',
    },
    {
        'code': 'GH',
        'name': 'Ghana',
        'region': 'West Africa',
        'authority': 'Data Protection Commission, Ghana',
        'authority_url': 'https://dataprotection.org.gh/',
        'flag_emoji': '🇬🇭',
    },
    {
        'code': 'KE',
        'name': 'Kenya',
        'region': 'East Africa',
        'authority': 'Office of the Data Protection Commissioner',
        'authority_url': 'https://www.odpc.go.ke/',
        'flag_emoji': '🇰🇪',
    },
    {
        'code': 'NG',
        'name': 'Nigeria',
        'region': 'West Africa',
        'authority': 'Nigeria Data Protection Commission',
        'authority_url': 'https://ndpc.gov.ng/',
        'flag_emoji': '🇳🇬',
    },
    {
        'code': 'US',
        'name': 'United States (California)',
        'region': 'North America',
        'authority': 'California Privacy Protection Agency',
        'authority_url': 'https://cppa.ca.gov/',
        'flag_emoji': '🇺🇸',
    },
]

FRAMEWORKS = [
    {
        'jurisdiction_code': 'EU',
        'code': 'GDPR',
        'short_name': 'GDPR',
        'long_name': 'General Data Protection Regulation (Regulation (EU) 2016/679)',
        'enacted_year': 2016,
        'reference_url': 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
        'max_fine_description': 'Up to €20m or 4% of annual global turnover, whichever is higher.',
        'summary': 'The European regulation governing processing of personal data of EU/EEA residents, with extraterritorial reach.',
    },
    {
        'jurisdiction_code': 'GH',
        'code': 'GH-DPA-2012',
        'short_name': 'Ghana DPA 2012',
        'long_name': 'Data Protection Act, 2012 (Act 843)',
        'enacted_year': 2012,
        'reference_url': 'https://dataprotection.org.gh/',
        'max_fine_description': 'Up to GHS 90,000 or 10 years imprisonment (varies per offence); administrative sanctions.',
        'summary': 'Ghana\'s principal data protection statute establishing the Data Protection Commission and registration regime.',
    },
    {
        'jurisdiction_code': 'KE',
        'code': 'KE-DPA-2019',
        'short_name': 'Kenya DPA 2019',
        'long_name': 'The Data Protection Act, 2019 (No. 24 of 2019)',
        'enacted_year': 2019,
        'reference_url': 'https://www.odpc.go.ke/',
        'max_fine_description': 'Up to KES 5 million or 1% of annual turnover, whichever is lower.',
        'summary': 'Kenya\'s GDPR-inspired framework enforced by the ODPC, including registration and breach notification.',
    },
    {
        'jurisdiction_code': 'NG',
        'code': 'NG-NDPA-2023',
        'short_name': 'Nigeria NDPA 2023',
        'long_name': 'Nigeria Data Protection Act, 2023',
        'enacted_year': 2023,
        'reference_url': 'https://ndpc.gov.ng/',
        'max_fine_description': 'Up to ₦10m or 2% of annual gross revenue for data controllers of major importance.',
        'summary': 'Nigeria\'s primary data protection statute, replacing the NDPR regulatory regime and creating the NDPC.',
    },
    {
        'jurisdiction_code': 'US',
        'code': 'US-CCPA',
        'short_name': 'CCPA/CPRA',
        'long_name': 'California Consumer Privacy Act, as amended by the CPRA',
        'enacted_year': 2018,
        'reference_url': 'https://cppa.ca.gov/',
        'max_fine_description': 'Up to $7,500 per intentional violation; $2,500 per unintentional violation; statutory damages for breaches.',
        'summary': 'California\'s consumer privacy regime granting access, deletion, correction, and opt-out-of-sale/share rights.',
    },
]


# Keys:
# code, title, summary, category, citation, severity_weight, applicability_rule, guidance, typical_evidence
REQUIREMENTS = {
    'GDPR': [
        {
            'code': 'GDPR-Art-5', 'category': 'governance', 'citation': 'Art. 5',
            'title': 'Adhere to the principles of processing',
            'summary': 'Lawfulness, fairness, transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity/confidentiality, accountability.',
            'severity_weight': 5,
            'guidance': 'Document how each principle is operationalised. Map data flows end-to-end. Keep a single source of truth for processing activities.',
            'typical_evidence': 'Written data protection policy citing Art. 5; ROPA; training records.',
        },
        {
            'code': 'GDPR-Art-6', 'category': 'lawful_basis', 'citation': 'Art. 6',
            'title': 'Establish a lawful basis for each processing activity',
            'summary': 'Identify and document one of the six lawful bases for every processing activity (consent, contract, legal obligation, vital interests, public task, legitimate interests).',
            'severity_weight': 5,
            'guidance': 'Create a processing inventory and assign a lawful basis to each. For legitimate interests, complete an LIA.',
            'typical_evidence': 'ROPA showing lawful basis per activity; signed LIAs.',
        },
        {
            'code': 'GDPR-Art-12', 'category': 'transparency', 'citation': 'Arts. 12-14',
            'title': 'Provide transparent information to data subjects',
            'summary': 'Provide a concise, intelligible privacy notice covering identity of controller, purposes, legal basis, recipients, retention, rights, and contact for the DPO.',
            'severity_weight': 4,
            'guidance': 'Publish layered privacy notices at collection points. Review at least annually.',
            'typical_evidence': 'Live privacy notice with last-reviewed date; consent banner copy.',
        },
        {
            'code': 'GDPR-Art-15', 'category': 'rights', 'citation': 'Arts. 15-22',
            'title': 'Honor data subject rights within one month',
            'summary': 'Access, rectification, erasure, restriction, portability, objection, and opt-out of automated decisions must be processed within one calendar month (extendable by two months for complexity).',
            'severity_weight': 5,
            'guidance': 'Stand up a DSAR intake channel and a tracked workflow with SLAs.',
            'typical_evidence': 'DSAR register with received/acknowledged/responded timestamps.',
        },
        {
            'code': 'GDPR-Art-30', 'category': 'ropa', 'citation': 'Art. 30',
            'title': 'Maintain Records of Processing Activities (ROPA)',
            'summary': 'Controllers and processors must maintain a written register of processing activities listing purposes, categories of data and subjects, recipients, transfers, retention, and security measures.',
            'severity_weight': 5,
            'guidance': 'Use a structured register (template provided). Update on every new processing activity.',
            'typical_evidence': 'ROPA spreadsheet/register with last-updated timestamp.',
        },
        {
            'code': 'GDPR-Art-32', 'category': 'security', 'citation': 'Art. 32',
            'title': 'Implement appropriate technical and organisational measures (TOMs)',
            'summary': 'Encryption, pseudonymisation, availability/integrity, regular testing, and ability to restore availability.',
            'severity_weight': 5,
            'guidance': 'Maintain a security control baseline (ISO 27001 / NIST CSF / CIS). Document encryption-in-transit and at-rest.',
            'typical_evidence': 'Security policy; encryption configuration evidence; pen-test report.',
        },
        {
            'code': 'GDPR-Art-33', 'category': 'breach', 'citation': 'Arts. 33-34',
            'title': 'Breach notification within 72 hours',
            'summary': 'Personal data breaches must be notified to the supervisory authority within 72 hours of becoming aware, and affected data subjects notified if high risk.',
            'severity_weight': 5,
            'guidance': 'Stand up an incident playbook with named roles and a pre-drafted notification template.',
            'typical_evidence': 'Incident response policy; breach register; tabletop exercise notes.',
        },
        {
            'code': 'GDPR-Art-35', 'category': 'dpia', 'citation': 'Art. 35',
            'title': 'Perform DPIA for high-risk processing',
            'applicability_rule': 'requires_dpia',
            'summary': 'A Data Protection Impact Assessment is mandatory for processing likely to result in high risk to rights and freedoms (profiling, large-scale special category, children\'s data, public monitoring).',
            'severity_weight': 4,
            'guidance': 'Use a repeatable DPIA template and require sign-off by the DPO for all high-risk initiatives.',
            'typical_evidence': 'Completed DPIAs signed by the DPO; DPIA register.',
        },
        {
            'code': 'GDPR-Art-37', 'category': 'governance', 'citation': 'Arts. 37-39',
            'title': 'Appoint a Data Protection Officer (DPO) where required',
            'applicability_rule': 'requires_dpo',
            'summary': 'A DPO is required for public authorities, large-scale monitoring, or large-scale special-category data processing.',
            'severity_weight': 3,
            'guidance': 'Publish the DPO\'s contact details and register them with the supervisory authority where required.',
            'typical_evidence': 'DPO appointment letter; contact published in privacy notice.',
        },
        {
            'code': 'GDPR-Chap-V', 'category': 'transfers', 'citation': 'Arts. 44-50',
            'title': 'Use a valid transfer mechanism for data leaving the EEA',
            'applicability_rule': 'requires_transfer_mechanism',
            'summary': 'Transfers outside the EEA require an adequacy decision, SCCs, BCRs, or a valid derogation; complete a Transfer Impact Assessment where applicable.',
            'severity_weight': 5,
            'guidance': 'Inventory sub-processors, map their locations, and document the transfer mechanism for each.',
            'typical_evidence': 'Signed SCCs; TIAs; sub-processor register.',
        },
    ],

    'GH-DPA-2012': [
        {
            'code': 'GH-Registration', 'category': 'registration', 'citation': 'Act 843 §§27-29',
            'title': 'Register as a data controller with the Data Protection Commission',
            'summary': 'All data controllers processing personal data in Ghana must register with the DPC and renew annually.',
            'severity_weight': 5,
            'guidance': 'Complete registration via the DPC portal. Maintain registration certificate for inspection.',
            'typical_evidence': 'Valid DPC registration certificate.',
        },
        {
            'code': 'GH-Principles', 'category': 'governance', 'citation': 'Act 843 §17',
            'title': 'Apply the eight data protection principles',
            'summary': 'Accountability, lawfulness, specification of purpose, compatibility of further processing, quality, openness, safeguards, data subject participation.',
            'severity_weight': 5,
            'guidance': 'Adopt a written policy tracking each principle to an operational control.',
            'typical_evidence': 'Policy; training records.',
        },
        {
            'code': 'GH-Consent', 'category': 'lawful_basis', 'citation': 'Act 843 §20',
            'title': 'Obtain consent or rely on a lawful processing ground',
            'summary': 'Processing requires consent or another lawful ground (contract, legal obligation, vital interests, public interest, legitimate interests).',
            'severity_weight': 4,
            'guidance': 'Record consent where relied on and make withdrawal as easy as giving it.',
            'typical_evidence': 'Consent logs with timestamps and withdrawal mechanism.',
        },
        {
            'code': 'GH-Notice', 'category': 'transparency', 'citation': 'Act 843 §24',
            'title': 'Provide notice to data subjects at collection',
            'summary': 'Inform subjects of the purposes, recipients, rights, consequences of refusal, and contact for the controller.',
            'severity_weight': 4,
            'guidance': 'Maintain a jurisdictional privacy notice; surface at every collection point.',
            'typical_evidence': 'Privacy notice live on site and products.',
        },
        {
            'code': 'GH-Security', 'category': 'security', 'citation': 'Act 843 §28',
            'title': 'Safeguard data against loss and unauthorised access',
            'summary': 'Reasonable technical and organisational measures to preserve integrity and confidentiality of personal data.',
            'severity_weight': 5,
            'guidance': 'Adopt recognised security baselines (ISO/NIST); encrypt and back up; restrict access on least-privilege.',
            'typical_evidence': 'Information security policy; access review logs.',
        },
        {
            'code': 'GH-Rights', 'category': 'rights', 'citation': 'Act 843 §§32-37',
            'title': 'Facilitate data subject rights of access and correction',
            'summary': 'Data subjects may access their data, request correction, and object to processing.',
            'severity_weight': 4,
            'guidance': 'Stand up a DSAR workflow — Ghana requires responses within a reasonable time.',
            'typical_evidence': 'DSAR register.',
        },
        {
            'code': 'GH-Transfers', 'category': 'transfers', 'citation': 'Act 843 §47',
            'title': 'Ensure lawful cross-border transfers',
            'applicability_rule': 'requires_transfer_mechanism',
            'summary': 'Transfers to countries without an adequate regime require safeguards or consent.',
            'severity_weight': 4,
            'guidance': 'Inventory cross-border transfers; obtain DPC guidance where unsure.',
            'typical_evidence': 'Transfer register; contracts with processors abroad.',
        },
    ],

    'KE-DPA-2019': [
        {
            'code': 'KE-Registration', 'category': 'registration', 'citation': 'DPA §18',
            'title': 'Register as data controller or processor with the ODPC',
            'summary': 'Controllers and processors above a prescribed threshold must register with the ODPC (renewable every 2 years).',
            'severity_weight': 5,
            'guidance': 'Register via the ODPC online portal; maintain the certificate for inspection.',
            'typical_evidence': 'ODPC registration certificate.',
        },
        {
            'code': 'KE-Principles', 'category': 'governance', 'citation': 'DPA §25',
            'title': 'Apply data protection principles',
            'summary': 'Lawfulness, purpose limitation, minimisation, accuracy, storage limitation, integrity/confidentiality.',
            'severity_weight': 5,
            'guidance': 'Codify principles in a written policy owned by a named privacy lead.',
            'typical_evidence': 'Policy; training.',
        },
        {
            'code': 'KE-Consent', 'category': 'lawful_basis', 'citation': 'DPA §30',
            'title': 'Establish a lawful basis',
            'summary': 'One of: consent, contract, legal obligation, vital interests, public task, legitimate interests.',
            'severity_weight': 5,
            'guidance': 'Map each processing activity to a lawful basis in the ROPA.',
            'typical_evidence': 'ROPA with lawful basis column.',
        },
        {
            'code': 'KE-Notice', 'category': 'transparency', 'citation': 'DPA §29',
            'title': 'Provide information to data subjects',
            'summary': 'Notify subjects of rights, purposes, recipients, retention, and contacts.',
            'severity_weight': 4,
            'guidance': 'Maintain a Kenya-specific privacy notice referencing the ODPC and DPA §29.',
            'typical_evidence': 'Privacy notice.',
        },
        {
            'code': 'KE-Rights', 'category': 'rights', 'citation': 'DPA §26, §40',
            'title': 'Respect data subject rights',
            'summary': 'Access, rectification, erasure, restriction, portability, objection to automated decision-making.',
            'severity_weight': 5,
            'guidance': 'Respond within a reasonable period (commonly 30 days).',
            'typical_evidence': 'DSAR register.',
        },
        {
            'code': 'KE-Breach', 'category': 'breach', 'citation': 'DPA §43',
            'title': 'Notify the ODPC of breaches within 72 hours',
            'summary': 'Controllers must notify the ODPC within 72 hours of becoming aware; data subjects where there is real risk of harm.',
            'severity_weight': 5,
            'guidance': 'Stand up an incident response runbook with ODPC contact.',
            'typical_evidence': 'Incident response plan; breach register.',
        },
        {
            'code': 'KE-DPIA', 'category': 'dpia', 'citation': 'DPA §31',
            'title': 'Complete DPIA for high-risk processing',
            'applicability_rule': 'requires_dpia',
            'summary': 'DPIAs required for processing likely to result in high risk to rights and freedoms.',
            'severity_weight': 4,
            'guidance': 'Use the DPIA template; submit to ODPC where residual risk is high.',
            'typical_evidence': 'Signed DPIAs.',
        },
        {
            'code': 'KE-Transfers', 'category': 'transfers', 'citation': 'DPA §§48-50',
            'title': 'Ensure lawful cross-border transfers',
            'applicability_rule': 'requires_transfer_mechanism',
            'summary': 'Transfers out of Kenya require adequacy, appropriate safeguards, or an applicable exemption.',
            'severity_weight': 5,
            'guidance': 'Complete a Kenya-specific Transfer Impact Assessment.',
            'typical_evidence': 'Transfer register; TIAs.',
        },
    ],

    'NG-NDPA-2023': [
        {
            'code': 'NG-Principles', 'category': 'governance', 'citation': 'NDPA §24',
            'title': 'Observe principles of personal data processing',
            'summary': 'Lawfulness, fairness, transparency, purpose specification, accuracy, storage limitation, integrity and confidentiality, accountability.',
            'severity_weight': 5,
            'guidance': 'Codify in a written policy aligned with the NDPC\'s implementation directives.',
            'typical_evidence': 'Policy; training.',
        },
        {
            'code': 'NG-Lawful', 'category': 'lawful_basis', 'citation': 'NDPA §25',
            'title': 'Establish a lawful basis',
            'summary': 'One of: consent, contract, legal obligation, vital interests, public interest, legitimate interests.',
            'severity_weight': 5,
            'guidance': 'Map each activity to a lawful basis and document in ROPA.',
            'typical_evidence': 'ROPA.',
        },
        {
            'code': 'NG-Notice', 'category': 'transparency', 'citation': 'NDPA §27',
            'title': 'Provide privacy information to data subjects',
            'summary': 'Notify subjects of identity, purposes, recipients, retention, rights, and NDPC complaint channel.',
            'severity_weight': 4,
            'guidance': 'Publish an NDPA-specific privacy notice referencing the NDPC.',
            'typical_evidence': 'Privacy notice.',
        },
        {
            'code': 'NG-Rights', 'category': 'rights', 'citation': 'NDPA §§34-39',
            'title': 'Honour data subject rights',
            'summary': 'Access, rectification, erasure, restriction, portability, objection, opt-out of automated decisions.',
            'severity_weight': 5,
            'guidance': 'Operate a DSAR workflow with defined SLAs.',
            'typical_evidence': 'DSAR register.',
        },
        {
            'code': 'NG-Security', 'category': 'security', 'citation': 'NDPA §39',
            'title': 'Implement appropriate technical and organisational measures',
            'summary': 'Protect against unauthorised access, loss, destruction, alteration, or disclosure.',
            'severity_weight': 5,
            'guidance': 'Adopt a recognised security baseline; conduct regular assessments.',
            'typical_evidence': 'Security policy; assessment reports.',
        },
        {
            'code': 'NG-Breach', 'category': 'breach', 'citation': 'NDPA §40',
            'title': 'Notify the NDPC of breaches within 72 hours',
            'summary': 'Notify the NDPC within 72 hours of becoming aware; data subjects where there is real risk of harm.',
            'severity_weight': 5,
            'guidance': 'Prepare notification template addressed to the NDPC in advance.',
            'typical_evidence': 'Incident response plan; breach register.',
        },
        {
            'code': 'NG-DPO', 'category': 'governance', 'citation': 'NDPA §32',
            'title': 'Appoint a Data Protection Officer where required',
            'applicability_rule': 'requires_dpo',
            'summary': 'Controllers of major importance and processors of high-risk data must appoint a DPO and publish their contact.',
            'severity_weight': 4,
            'guidance': 'Document DPO appointment and register where required.',
            'typical_evidence': 'DPO appointment letter.',
        },
        {
            'code': 'NG-ROPA', 'category': 'ropa', 'citation': 'NDPA §29',
            'title': 'Maintain records of processing activities',
            'summary': 'Controllers and processors of major importance must maintain written processing records.',
            'severity_weight': 5,
            'guidance': 'Use a structured ROPA updated on every new processing activity.',
            'typical_evidence': 'ROPA register.',
        },
        {
            'code': 'NG-Transfers', 'category': 'transfers', 'citation': 'NDPA §§41-43',
            'title': 'Ensure lawful cross-border transfers',
            'applicability_rule': 'requires_transfer_mechanism',
            'summary': 'Transfers permitted on basis of adequacy, appropriate safeguards, binding instruments, or exceptions.',
            'severity_weight': 5,
            'guidance': 'Inventory sub-processors and document the mechanism for each.',
            'typical_evidence': 'Transfer register.',
        },
    ],

    'US-CCPA': [
        {
            'code': 'CCPA-Notice', 'category': 'transparency', 'citation': 'Cal. Civ. Code §1798.100',
            'title': 'Provide notice at or before collection',
            'summary': 'Inform California consumers of categories collected, purposes, retention, and rights.',
            'severity_weight': 4,
            'guidance': 'Publish a California-specific notice or section; annually disclose categories and purposes.',
            'typical_evidence': 'Privacy policy with CCPA section; last-updated date.',
        },
        {
            'code': 'CCPA-Rights', 'category': 'rights', 'citation': '§1798.105-.125',
            'title': 'Honor consumer rights to know, delete, correct, and limit',
            'summary': 'Within 45 days (extendable by 45): access, deletion, correction, and limit use of sensitive personal information.',
            'severity_weight': 5,
            'guidance': 'Provide two or more designated methods for requests (web form + toll-free number).',
            'typical_evidence': 'Request intake pages; verification procedure; response register.',
        },
        {
            'code': 'CCPA-OptOut', 'category': 'rights', 'citation': '§1798.135',
            'title': 'Provide a "Do Not Sell or Share My Personal Information" link',
            'applicability_rule': 'requires_opt_out_sale',
            'summary': 'Businesses must provide a clear, conspicuous Do-Not-Sell/Share link and honor Global Privacy Control signals.',
            'severity_weight': 5,
            'guidance': 'Place the link in the footer; honour GPC at browser level.',
            'typical_evidence': 'Working Do-Not-Sell link; GPC honouring evidence.',
        },
        {
            'code': 'CCPA-Contracts', 'category': 'vendors', 'citation': '§1798.100(d)',
            'title': 'Flow-down contractual terms to service providers and contractors',
            'summary': 'Written contracts with required clauses (purpose limitation, no sale, audit rights).',
            'severity_weight': 4,
            'guidance': 'Use an addendum template; log every active DPA.',
            'typical_evidence': 'Signed DPAs with service providers.',
        },
        {
            'code': 'CCPA-Sensitive', 'category': 'special', 'citation': '§1798.121',
            'title': 'Provide "Limit Use" for Sensitive Personal Information',
            'summary': 'Consumers may direct businesses to limit use of sensitive PI to what is necessary to perform services.',
            'severity_weight': 4,
            'guidance': 'Map SPI; provide a separate "Limit the Use of My Sensitive Personal Information" link where applicable.',
            'typical_evidence': 'SPI map; Limit-Use mechanism.',
        },
        {
            'code': 'CCPA-Security', 'category': 'security', 'citation': '§1798.100(e)',
            'title': 'Implement reasonable security procedures',
            'summary': 'Protect personal information from unauthorised access, destruction, use, modification, or disclosure.',
            'severity_weight': 5,
            'guidance': 'Adopt a recognised baseline; statutory damages apply to breaches of unencrypted SPI.',
            'typical_evidence': 'Security programme documentation.',
        },
    ],
}


# Cross-jurisdictional mappings (source_code -> [(target_code, equivalence, note)])
CROSSWALK = [
    ('GDPR-Art-30', 'NG-ROPA', 'equivalent', 'Both require written records of processing activities.'),
    ('GDPR-Art-32', 'KE-Principles', 'stricter', 'GDPR Art. 32 is a dedicated security provision; Kenya treats security under principles.'),
    ('GDPR-Art-33', 'KE-Breach', 'equivalent', 'Both set a 72-hour notification window.'),
    ('GDPR-Art-33', 'NG-Breach', 'equivalent', 'NDPA mirrors the 72-hour notification window.'),
    ('GDPR-Art-6', 'GH-Consent', 'equivalent', 'Six lawful bases mirrored; Ghana recognises consent + 5 others.'),
    ('GDPR-Art-6', 'KE-Consent', 'equivalent', 'Kenya DPA §30 closely mirrors GDPR Art. 6.'),
    ('GDPR-Art-6', 'NG-Lawful', 'equivalent', 'NDPA §25 mirrors GDPR Art. 6.'),
    ('GDPR-Art-12', 'CCPA-Notice', 'partial', 'CCPA notice obligations are narrower (California-specific) but conceptually similar.'),
    ('GDPR-Art-15', 'CCPA-Rights', 'partial', 'CCPA provides access/delete/correct; GDPR extends to portability and objection.'),
    ('GDPR-Art-35', 'KE-DPIA', 'equivalent', 'Kenya DPA §31 mirrors GDPR DPIA trigger.'),
    ('GDPR-Chap-V', 'KE-Transfers', 'equivalent', 'Similar mechanisms (adequacy, safeguards, derogations).'),
    ('GDPR-Chap-V', 'NG-Transfers', 'equivalent', 'NDPA transfer regime mirrors GDPR mechanisms.'),
    ('GDPR-Chap-V', 'GH-Transfers', 'weaker', 'Ghana\'s transfer regime is less detailed than GDPR.'),
]
