# Generated by Django 5.1.15 on 2026-04-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jurisdictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Initial applicability assessment', max_length=140)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('profile_snapshot', models.JSONField(default=dict, help_text='Snapshot of OrgProfile at run time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable', models.BooleanField()),
                ('rationale', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='assessments.assessment')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisdictions.framework')),
            ],
            options={
                'ordering': ['framework__jurisdiction__name'],
                'unique_together': {('assessment', 'framework')},
            },
        ),
        migrations.CreateModel(
            name='RequirementApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable', models.BooleanField()),
                ('rationale', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='assessments.assessment')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisdictions.requirement')),
            ],
            options={
                'unique_together': {('assessment', 'requirement')},
            },
        ),
    ]
