# Generated by Django 5.1.15 on 2026-04-22 13:19

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_orgprofile_data_categories_and_more'),
        ('dpia', '0001_initial'),
        ('retention', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('controller', 'Controller'), ('joint', 'Joint controller'), ('processor', 'Processor')], default='controller', max_length=16)),
                ('purposes', models.JSONField(default=list, help_text='Processing purposes from the canonical list.', validators=[core.validators.ListOfChoices([('service_delivery', 'Service delivery'), ('marketing', 'Marketing / Advertising'), ('analytics', 'Analytics / Product improvement'), ('fraud', 'Fraud prevention / Security'), ('hr', 'HR / Employment'), ('legal', 'Legal obligation / Tax / Accounting'), ('research', 'Research'), ('personalization', 'Personalization'), ('kyc', 'KYC / Regulatory verification')])])),
                ('lawful_basis', models.CharField(choices=[('consent', 'Consent (Art. 6(1)(a))'), ('contract', 'Contract (Art. 6(1)(b))'), ('legal_obligation', 'Legal obligation (Art. 6(1)(c))'), ('vital_interests', 'Vital interests (Art. 6(1)(d))'), ('public_task', 'Public task (Art. 6(1)(e))'), ('legitimate_interests', 'Legitimate interests (Art. 6(1)(f))')], default='contract', max_length=24)),
                ('special_category_basis', models.CharField(choices=[('none', 'Not processing special categories'), ('explicit_consent', 'Explicit consent (Art. 9(2)(a))'), ('employment', 'Employment / social security (Art. 9(2)(b))'), ('vital', 'Vital interests (Art. 9(2)(c))'), ('non_profit', 'Not-for-profit activity (Art. 9(2)(d))'), ('public', 'Data made public by subject (Art. 9(2)(e))'), ('legal_claims', 'Legal claims (Art. 9(2)(f))'), ('substantial_public', 'Substantial public interest (Art. 9(2)(g))'), ('health', 'Preventive / occupational / public health (Art. 9(2)(h)-(i))'), ('archiving', 'Archiving / research / statistics (Art. 9(2)(j))')], default='none', max_length=24)),
                ('lawful_basis_note', models.TextField(blank=True, help_text='For legitimate interests, include the LIA outcome summary.')),
                ('data_categories', models.JSONField(default=list, validators=[core.validators.ListOfChoices([('general_pii', 'General personal data'), ('contact', 'Contact details'), ('financial', 'Financial'), ('health', 'Health / Medical'), ('biometric', 'Biometric'), ('location', 'Location / Geolocation'), ('children', 'Data of minors (children)'), ('behavioral', 'Behavioral / Profiling'), ('special_category', 'Special category (race, religion, union, sexual orientation, political)'), ('criminal', 'Criminal convictions'), ('credentials', 'Authentication credentials'), ('government_id', 'Government-issued ID')])])),
                ('data_subject_categories', models.JSONField(default=list, validators=[core.validators.ListOfChoices([('customers', 'Customers / end users'), ('prospects', 'Prospects / leads'), ('employees', 'Employees'), ('contractors', 'Contractors / vendors'), ('visitors', 'Website visitors'), ('children', 'Children (<16 or local equivalent)'), ('patients', 'Patients'), ('students', 'Students'), ('job_applicants', 'Job applicants'), ('third_parties', 'Third parties')])])),
                ('recipients', models.JSONField(default=list, help_text='Free-text list of internal recipients + processor / sub-processor names.', validators=[core.validators.ListOfStrings()])),
                ('internal_systems', models.JSONField(default=list, help_text='Internal systems / data stores processing this activity.', validators=[core.validators.ListOfStrings()])),
                ('cross_border_transfers', models.BooleanField(default=False)),
                ('transfer_countries', models.JSONField(default=list, help_text='ISO country codes of destination jurisdictions.', validators=[core.validators.ListOfStrings()])),
                ('transfer_mechanism', models.CharField(blank=True, choices=[('scc', 'Standard Contractual Clauses'), ('bcr', 'Binding Corporate Rules'), ('adequacy', 'Adequacy decision'), ('derogation', 'Derogation (Art. 49 GDPR / equivalent)'), ('consent', 'Explicit consent'), ('none', 'No mechanism in place')], max_length=24)),
                ('retention_note', models.CharField(blank=True, max_length=240)),
                ('security_measures', models.TextField(blank=True, help_text='Technical and organisational measures (TOMs) applied.')),
                ('dpia_required', models.BooleanField(default=False)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('dpia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='dpia.dpia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_processing_activities', to=settings.AUTH_USER_MODEL)),
                ('retention_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='retention.retentionpolicy')),
            ],
            options={
                'verbose_name': 'processing activity',
                'verbose_name_plural': 'processing activities (ROPA)',
                'ordering': ['name'],
            },
        ),
    ]
