# Generated by Django 5.1.15 on 2026-04-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('privacy_notice', 'Privacy Notice / Policy'), ('ropa', 'Record of Processing Activities (ROPA)'), ('dsar_response', 'DSAR Response'), ('dpia', 'Data Protection Impact Assessment'), ('breach_notification', 'Regulator Breach Notification'), ('dpa_clauses', 'Data Processing Agreement clauses'), ('cookie_policy', 'Cookie Policy')], max_length=32)),
                ('jurisdiction_code', models.CharField(blank=True, help_text='Empty = universal', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(help_text='Django-template string. Context = {org, profile, jurisdiction, frameworks, today}.')),
                ('version', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['kind', 'jurisdiction_code'],
                'unique_together': {('kind', 'jurisdiction_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('rendered_content', models.TextField()),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='templates_engine.templatedefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
