# Generated by Django 5.1.15 on 2026-04-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdictions', '0001_initial'),
        ('templates_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedefinition',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Requirements this template helps satisfy.', related_name='templates', to='jurisdictions.requirement'),
        ),
    ]
