# Generated by Django 5.1.15 on 2026-04-22 13:02

import controls.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'md', 'json', 'log']), controls.models._validate_file_size]),
        ),
        migrations.CreateModel(
            name='ControlStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('verified', 'Verified'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('to_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('verified', 'Verified'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='controls.control')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['control', '-created_at'], name='controls_co_control_84af47_idx')],
            },
        ),
    ]
