# Generated by Django 5.1.15 on 2026-04-22 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authevent'),
        ('controls', '0002_alter_evidence_file_controlstatuschange'),
        ('jurisdictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['organization', 'status'], name='controls_co_organiz_e30c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['organization', 'due_date'], name='controls_co_organiz_0752d6_idx'),
        ),
    ]
