# Generated by Django 5.1.15 on 2026-04-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jurisdictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='e.g. breach, cross-border, vendor', max_length=40)),
                ('likelihood', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Elevated'), (4, 'High'), (5, 'Severe')], default=2)),
                ('impact', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Elevated'), (4, 'High'), (5, 'Severe')], default=2)),
                ('data_sensitivity', models.PositiveSmallIntegerField(default=2, help_text='1 (low) to 5 (special category / children / biometric)')),
                ('data_volume_log10', models.PositiveSmallIntegerField(default=3, help_text='log10 of estimated subjects affected (3 = 1k, 4 = 10k, 5 = 100k, 6 = 1M)')),
                ('regulator_activity', models.PositiveSmallIntegerField(default=2, help_text='1 (quiet) to 5 (very active) — weight for regulator activity in affected jurisdictions')),
                ('control_effectiveness', models.PositiveSmallIntegerField(default=50, help_text='0–100 percent — estimated effectiveness of controls in place')),
                ('treatment', models.CharField(choices=[('accept', 'Accept'), ('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('avoid', 'Avoid')], default='mitigate', max_length=12)),
                ('treatment_notes', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('inherent_score', models.PositiveIntegerField(default=0)),
                ('residual_score', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=10)),
                ('linked_requirements', models.ManyToManyField(blank=True, related_name='linked_risks', to='jurisdictions.requirement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-residual_score', 'title'],
            },
        ),
    ]
