# Generated by Django 5.1.15 on 2026-04-22 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authevent'),
        ('jurisdictions', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['organization', '-residual_score'], name='risks_risk_organiz_4fd9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['organization', 'severity'], name='risks_risk_organiz_f0d748_idx'),
        ),
    ]
