# Generated by Django 5.1.15 on 2026-04-22 11:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(help_text='ISO-3166 alpha-2 code of HQ', max_length=2)),
                ('revenue_band', models.CharField(blank=True, choices=[('<1M', 'Under $1M'), ('1-10M', '$1M – $10M'), ('10-25M', '$10M – $25M'), ('25-100M', '$25M – $100M'), ('100M+', 'Over $100M')], max_length=12)),
                ('employee_band', models.CharField(blank=True, choices=[('1-10', '1 – 10'), ('11-50', '11 – 50'), ('51-250', '51 – 250'), ('251-1000', '251 – 1,000'), ('1000+', '1,000+')], max_length=12)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sectors', models.JSONField(default=list, help_text="Choices: ['fintech', 'health', 'ecommerce', 'saas', 'education', 'telecom', 'ngo', 'public', 'media', 'other']")),
                ('data_categories', models.JSONField(default=list, help_text="Choices: ['general_pii', 'contact', 'financial', 'health', 'biometric', 'location', 'children', 'behavioral', 'special_category', 'criminal', 'credentials', 'government_id']")),
                ('processing_purposes', models.JSONField(default=list, help_text="Choices: ['service_delivery', 'marketing', 'analytics', 'fraud', 'hr', 'legal', 'research', 'personalization', 'kyc']")),
                ('data_subject_locations', models.JSONField(default=list, help_text='ISO alpha-2 country codes where data subjects reside (e.g. ["GH","NG","KE","DE","US-CA"])')),
                ('has_establishment_in', models.JSONField(default=list, help_text='Countries where the organization has an establishment')),
                ('processes_eu_residents', models.BooleanField(default=False)),
                ('offers_to_california_residents', models.BooleanField(default=False)),
                ('cross_border_transfers', models.BooleanField(default=False)),
                ('transfer_mechanisms', models.JSONField(default=list)),
                ('uses_automated_decision_making', models.BooleanField(default=False)),
                ('processes_childrens_data', models.BooleanField(default=False)),
                ('processes_health_data', models.BooleanField(default=False)),
                ('processes_biometric_data', models.BooleanField(default=False)),
                ('annual_data_subjects_estimate', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('dpo', 'Data Protection Officer'), ('compliance', 'Compliance Officer'), ('auditor', 'Auditor (read-only)'), ('viewer', 'Viewer')], default='owner', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text="User's active workspace")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
