# Generated by Django 5.1.15 on 2026-04-22 13:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='data_categories',
            field=models.JSONField(default=list, help_text="Choices: ['general_pii', 'contact', 'financial', 'health', 'biometric', 'location', 'children', 'behavioral', 'special_category', 'criminal', 'credentials', 'government_id']", validators=[core.validators.ListOfChoices([('general_pii', 'General personal data'), ('contact', 'Contact details'), ('financial', 'Financial'), ('health', 'Health / Medical'), ('biometric', 'Biometric'), ('location', 'Location / Geolocation'), ('children', 'Data of minors (children)'), ('behavioral', 'Behavioral / Profiling'), ('special_category', 'Special category (race, religion, union, sexual orientation, political)'), ('criminal', 'Criminal convictions'), ('credentials', 'Authentication credentials'), ('government_id', 'Government-issued ID')])]),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='data_subject_locations',
            field=models.JSONField(default=list, help_text='ISO alpha-2 country codes where data subjects reside (e.g. ["GH","NG","KE","DE","US-CA"])', validators=[core.validators.ListOfStrings()]),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='has_establishment_in',
            field=models.JSONField(default=list, help_text='Countries where the organization has an establishment', validators=[core.validators.ListOfStrings()]),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='processing_purposes',
            field=models.JSONField(default=list, help_text="Choices: ['service_delivery', 'marketing', 'analytics', 'fraud', 'hr', 'legal', 'research', 'personalization', 'kyc']", validators=[core.validators.ListOfChoices([('service_delivery', 'Service delivery'), ('marketing', 'Marketing / Advertising'), ('analytics', 'Analytics / Product improvement'), ('fraud', 'Fraud prevention / Security'), ('hr', 'HR / Employment'), ('legal', 'Legal obligation / Tax / Accounting'), ('research', 'Research'), ('personalization', 'Personalization'), ('kyc', 'KYC / Regulatory verification')])]),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='sectors',
            field=models.JSONField(default=list, help_text="Choices: ['fintech', 'health', 'ecommerce', 'saas', 'education', 'telecom', 'ngo', 'public', 'media', 'other']", validators=[core.validators.ListOfChoices([('fintech', 'Fintech / Financial services'), ('health', 'Healthcare'), ('ecommerce', 'E-commerce / Retail'), ('saas', 'SaaS / Software'), ('education', 'Education'), ('telecom', 'Telecom'), ('ngo', 'NGO / Non-profit'), ('public', 'Public sector'), ('media', 'Media / Advertising'), ('other', 'Other')])]),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='transfer_mechanisms',
            field=models.JSONField(default=list, validators=[core.validators.ListOfChoices([('scc', 'Standard Contractual Clauses'), ('bcr', 'Binding Corporate Rules'), ('adequacy', 'Adequacy decision'), ('derogation', 'Derogation (Art. 49 GDPR / equivalent)'), ('consent', 'Explicit consent'), ('none', 'No mechanism in place')])]),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='membership_one_primary_per_user'),
        ),
    ]
