# Generated by Django 5.1.15 on 2026-04-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_orgprofile_data_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username_attempted', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(choices=[('login_ok', 'Login succeeded'), ('login_fail', 'Login failed'), ('logout', 'Logout'), ('password_change', 'Password changed'), ('account_delete', 'Account deleted'), ('data_export', 'Data export requested')], max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_au_created_c00637_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_1923c7_idx'), models.Index(fields=['kind', '-created_at'], name='accounts_au_kind_aafa08_idx')],
            },
        ),
    ]
