# Generated by Django 5.1.15 on 2026-04-22 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSARRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(max_length=160)),
                ('subject_email', models.EmailField(max_length=254)),
                ('subject_country', models.CharField(blank=True, max_length=2)),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('rectification', 'Rectification'), ('erasure', 'Erasure / Deletion'), ('restriction', 'Restriction of processing'), ('portability', 'Portability'), ('objection', 'Objection'), ('automated_decision', 'Opt-out of automated decisions'), ('opt_out_sale', 'Opt-out of sale/share (CCPA)')], max_length=24)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verifying', 'Verifying identity'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='received', max_length=16)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
