# Generated by Django 5.1.15 on 2026-04-22 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authevent'),
        ('dsar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dsarrequest',
            index=models.Index(fields=['organization', 'status'], name='dsar_dsarre_organiz_7cbeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='dsarrequest',
            index=models.Index(fields=['organization', '-received_at'], name='dsar_dsarre_organiz_88e435_idx'),
        ),
    ]
