# Generated by Django 5.1.15 on 2026-04-22 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_orgprofile_data_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('data_category', models.CharField(choices=[('general_pii', 'General personal data'), ('contact', 'Contact details'), ('financial', 'Financial'), ('health', 'Health / Medical'), ('biometric', 'Biometric'), ('location', 'Location / Geolocation'), ('children', 'Data of minors (children)'), ('behavioral', 'Behavioral / Profiling'), ('special_category', 'Special category (race, religion, union, sexual orientation, political)'), ('criminal', 'Criminal convictions'), ('credentials', 'Authentication credentials'), ('government_id', 'Government-issued ID')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('retention_months', models.PositiveSmallIntegerField(help_text='Number of months data is retained after the trigger event.')),
                ('trigger', models.CharField(choices=[('collection', 'From date of collection'), ('last_interaction', 'From last interaction'), ('contract_end', 'From contract termination'), ('legal_hold_end', 'From end of legal hold'), ('transaction_date', 'From transaction date')], default='collection', max_length=24)),
                ('legal_basis', models.CharField(blank=True, help_text='Citation that justifies this retention period (e.g. "Tax Act §12 — 6 years").', max_length=240)),
                ('destruction_method', models.CharField(choices=[('delete', 'Secure deletion'), ('anonymise', 'Anonymisation'), ('pseudonymise', 'Pseudonymisation'), ('archive', 'Cold archive')], default='delete', max_length=16)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('legal_hold', models.BooleanField(default=False, help_text='If true, suspend automatic destruction (litigation / investigation).')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_retention_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'retention policies',
                'ordering': ['data_category', 'name'],
            },
        ),
    ]
