# Generated by Django 5.1.15 on 2026-04-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('processor', 'Processor'), ('sub_processor', 'Sub-processor'), ('controller', 'Controller (joint)')], default='processor', max_length=40)),
                ('country', models.CharField(help_text='ISO-3166 alpha-2 code', max_length=2)),
                ('data_categories', models.JSONField(default=list)),
                ('purposes', models.JSONField(default=list)),
                ('dpa_on_file', models.BooleanField(default=False)),
                ('dpa_expires_on', models.DateField(blank=True, null=True)),
                ('transfer_mechanism', models.CharField(blank=True, max_length=40)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
