# Generated by Django 5.1.15 on 2026-04-22 13:19

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='last_reviewed',
        ),
        migrations.AddField(
            model_name='vendor',
            name='certifications',
            field=models.JSONField(default=list, help_text='Certifications held, e.g. ["ISO 27001", "SOC 2 Type II", "ISO 27701"].', validators=[core.validators.ListOfStrings()]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='dpa_document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='dpa_signed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_security_audit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='next_security_audit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_tier',
            field=models.CharField(choices=[('low', 'Low (non-personal or pseudonymised)'), ('medium', 'Medium (business PII)'), ('high', 'High (sensitive / financial / health)'), ('critical', 'Critical (special category at scale)')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sub_processor_countries',
            field=models.JSONField(default=list, help_text='Countries where the vendor stores or processes data.', validators=[core.validators.ListOfStrings()]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tia_completed',
            field=models.BooleanField(default=False, help_text='Transfer Impact Assessment completed (post-Schrems II).'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='data_categories',
            field=models.JSONField(default=list, validators=[core.validators.ListOfChoices([('general_pii', 'General personal data'), ('contact', 'Contact details'), ('financial', 'Financial'), ('health', 'Health / Medical'), ('biometric', 'Biometric'), ('location', 'Location / Geolocation'), ('children', 'Data of minors (children)'), ('behavioral', 'Behavioral / Profiling'), ('special_category', 'Special category (race, religion, union, sexual orientation, political)'), ('criminal', 'Criminal convictions'), ('credentials', 'Authentication credentials'), ('government_id', 'Government-issued ID')])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='purposes',
            field=models.JSONField(default=list, validators=[core.validators.ListOfChoices([('service_delivery', 'Service delivery'), ('marketing', 'Marketing / Advertising'), ('analytics', 'Analytics / Product improvement'), ('fraud', 'Fraud prevention / Security'), ('hr', 'HR / Employment'), ('legal', 'Legal obligation / Tax / Accounting'), ('research', 'Research'), ('personalization', 'Personalization'), ('kyc', 'KYC / Regulatory verification')])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='role',
            field=models.CharField(choices=[('processor', 'Processor'), ('sub_processor', 'Sub-processor'), ('joint', 'Joint controller')], default='processor', max_length=16),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='transfer_mechanism',
            field=models.CharField(blank=True, choices=[('scc', 'Standard Contractual Clauses'), ('bcr', 'Binding Corporate Rules'), ('adequacy', 'Adequacy decision'), ('derogation', 'Derogation (Art. 49 GDPR / equivalent)'), ('consent', 'Explicit consent'), ('none', 'No mechanism in place')], max_length=16),
        ),
    ]
