# Generated by Django 5.1.15 on 2026-04-22 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authevent'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'status'], name='incidents_i_organiz_09b358_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', '-detected_at'], name='incidents_i_organiz_ece8be_idx'),
        ),
    ]
