# Generated by Django 5.1.15 on 2026-04-22 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_orgprofile_data_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DPIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected — do not proceed'), ('referred', 'Referred to regulator')], default='draft', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('proceed', 'Proceed'), ('conditions', 'Proceed with conditions'), ('consult', 'Consult regulator (Art. 36)'), ('halt', 'Do not proceed')], max_length=16)),
                ('trigger_automated_decisions', models.BooleanField(default=False)),
                ('trigger_large_scale_special', models.BooleanField(default=False)),
                ('trigger_systematic_monitoring', models.BooleanField(default=False)),
                ('trigger_sensitive_combined', models.BooleanField(default=False)),
                ('trigger_new_technology', models.BooleanField(default=False)),
                ('trigger_children', models.BooleanField(default=False)),
                ('trigger_vulnerable_subjects', models.BooleanField(default=False)),
                ('trigger_data_matching', models.BooleanField(default=False)),
                ('trigger_denies_service', models.BooleanField(default=False)),
                ('inherent_likelihood', models.PositiveSmallIntegerField(default=3, help_text='1-5')),
                ('inherent_impact', models.PositiveSmallIntegerField(default=3, help_text='1-5')),
                ('residual_likelihood', models.PositiveSmallIntegerField(default=2, help_text='1-5')),
                ('residual_impact', models.PositiveSmallIntegerField(default=2, help_text='1-5')),
                ('consultation_summary', models.TextField(blank=True)),
                ('mitigations', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_owner_of_dpias', to=settings.AUTH_USER_MODEL)),
                ('dpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpo_of_dpias', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'DPIA',
                'verbose_name_plural': 'DPIAs',
                'ordering': ['-created_at'],
            },
        ),
    ]
