# Generated by Django 5.1.15 on 2026-04-22 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_orgprofile_data_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required_months', models.PositiveSmallIntegerField(default=12, help_text='Completion must be refreshed every N months.')),
                ('audience_note', models.CharField(blank=True, help_text='Who must complete this module (e.g. "All staff handling customer data").', max_length=240)),
                ('resource_url', models.URLField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_on', models.DateField(default=django.utils.timezone.now)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('evidence_link', models.URLField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='training/%Y/%m/')),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='training.trainingmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_on'],
                'indexes': [models.Index(fields=['module', 'user', '-completed_on'], name='training_tr_module__1aeb9a_idx')],
            },
        ),
    ]
