# Generated by Django 5.1.15 on 2026-04-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ISO or region code, e.g. GH, KE, NG, US, EU', max_length=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('authority', models.CharField(blank=True, help_text='Regulator name', max_length=240)),
                ('authority_url', models.URLField(blank=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='e.g. GDPR, GH-DPA-2012, NDPA-2023, CCPA', max_length=40, unique=True)),
                ('short_name', models.CharField(max_length=60)),
                ('long_name', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('enacted_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reference_url', models.URLField(blank=True)),
                ('max_fine_description', models.CharField(blank=True, max_length=240)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='jurisdictions.jurisdiction')),
            ],
            options={
                'ordering': ['jurisdiction__name', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Citable reference, e.g. GDPR-Art-30', max_length=40)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('governance', 'Governance & Accountability'), ('lawful_basis', 'Lawful basis & consent'), ('transparency', 'Transparency & notices'), ('rights', 'Data subject rights'), ('security', 'Security of processing'), ('breach', 'Breach notification'), ('transfers', 'International transfers'), ('dpia', 'DPIA / Risk assessment'), ('vendors', 'Processors & sub-processors'), ('ropa', 'Record of processing'), ('retention', 'Retention & minimisation'), ('special', 'Special categories / children'), ('registration', 'Regulator registration'), ('automated', 'Automated decision-making')], max_length=20)),
                ('citation', models.CharField(blank=True, help_text='Article / Section reference', max_length=240)),
                ('severity_weight', models.PositiveSmallIntegerField(default=3, help_text='1 (low) – 5 (critical)')),
                ('applicability_rule', models.CharField(blank=True, help_text='Name of rule function in jurisdictions.applicability (empty = always applies if framework applies)', max_length=80)),
                ('guidance', models.TextField(blank=True, help_text='Practical steps the org should take')),
                ('typical_evidence', models.TextField(blank=True, help_text='Examples of evidence that satisfies this requirement')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jurisdictions.framework')),
            ],
            options={
                'ordering': ['framework', 'code'],
                'unique_together': {('framework', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RequirementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equivalence', models.CharField(choices=[('equivalent', 'Equivalent'), ('stricter', 'Target is stricter'), ('weaker', 'Target is weaker'), ('partial', 'Partial overlap')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_out', to='jurisdictions.requirement')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_in', to='jurisdictions.requirement')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
